### ISSUE TITLE
Feat: add `面包店` plugin

### ISSUE THREAD

**Issue by RShock** [zhenxun-org/zhenxun_bot_plugins_index#113]
| [面包店](https://github.com/RShock/nonebot-plugin-bread-shop)  [点击下载](https://github.com/RShock/nonebot-plugin-bread-shop/releases) | [@RShock](https://github.com/RShock) | 搬运nonebot的面包店，增加了氪金操作以回收群友金币 |

## 插件名

面包店

## GitHub 地址

[面包店](https://github.com/RShock/nonebot-plugin-bread-shop/tree/main)

## 备注

搬运nonebot的面包店插件，添加了需要金币才能进行的强制指令，从而消耗玩家的金币

## 下载地址（可选）

https://github.com/RShock/nonebot-plugin-bread-shop/releases/download/v0.0.1/nonebot_plugin_bread_shop.zip

**Comment by ChenPiTang-Hui** [comment]
大佬 我装了你插件之后发现变量{THING}
![Uploading Screenshot_2022-07-02-11-03-49-44_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()
![Uploading -2fcf13af319d94d5.png…]()

**Comment by ChenPiTang-Hui** [comment]
大佬我装了你插件后变量{THING}
![Screenshot_2022-07-02-11-03-49-44_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/69108232/176984481-a8c43866-55ef-42fc-a09c-5f9ea4262af8.jpg)
![-2fcf13af319d94d5](https://user-images.githubusercontent.com/69108232/176984482-c2e2168d-435c-44fa-8170-63f373ceae30.png)

**Comment by RShock** [comment]
拉了，我忘记加f了。
请把__init.py__里面的_zx_plugin_name__ = "{THING}店"换成__zx_plugin_name__ = f"{THING}店"
以快速修复这个问题
我后续再完善

**Comment by Judp28** [comment]
面包店很有意思，但是吃面包后的等级功能好像没什么用，可不可以给高等级的吃面包人一些奖励，比如说升级后发放金币？

**Comment by RShock** [comment]
这个插件的唯一作用就是把玩家的钱耗光。。
升级只有排行榜的作用。
正在做其他同类型（？）但是内容更丰富的插件

**Comment by Judp28** [comment]
> 这个插件的唯一作用就是把玩家的钱耗光。。 升级只有排行榜的作用。 正在做其他同类型（？）但是内容更丰富的插件

面包店不会做内容上的更新了吗？另外可以透露一下，新插件是指股海风云吗？

**Comment by RShock** [comment]
这个插件想再更新，我有点缺乏想象力，毕竟我也是搬运的
面包店最需要的是一个懒人化更新：可以1小时收1次，也可以10小时收1次（但是是10倍），用来防止大量刷屏
这个功能进一步推广，自然的就来到了挂机游戏的领域，让人想起了一些十年前的游戏，比如探险日志2.apk....
但是在这画饼也没啥用，想完成还得一段时间，更不要说后续繁琐的bug测试了

**Comment by Judp28** [comment]
> 这个插件想再更新，我有点缺乏想象力，毕竟我也是搬运的 面包店最需要的是一个懒人化更新：可以1小时收1次，也可以10小时收1次（但是是10倍），用来防止大量刷屏 这个功能进一步推广，自然的就来到了挂机游戏的领域，让人想起了一些十年前的游戏，比如探险日志2.apk.... 但是在这画饼也没啥用，想完成还得一段时间，更不要说后续繁琐的bug测试了

光是目前版本群友都玩的不亦乐乎了hhh，就是很耗金币，不知不觉金币就花光了，所以希望加一个根据面包等级可以领每日工资的设定
