### ISSUE TITLE
Feat: add `音游开字符` plugin

### ISSUE THREAD

**Issue by SEVEN-6174** [zhenxun-org/zhenxun_bot_plugins_index#191]
## 插件名

音游开字符

## GitHub 地址

https://github.com/SEVEN-6174/zhenxun_plugin_guessname

## 备注

最近很火（？）的音游群小游戏（虽然曲库不多）

**Comment by SEVEN-6174** [comment]
#190

**Comment by xuanerwa** [comment]
更新了
