### ISSUE TITLE
摸鱼日历运行报错

### ISSUE THREAD

**Issue by SuLiuming** [zhenxun-org/zhenxun_bot_plugins_index#192]
![image](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/assets/88638705/cbeab417-4fd8-44aa-a3b6-4cc1899d4709)
用的最新版真寻（就是改过数据库的那个）

**Comment by ayahana** [comment]
不是数据库的问题，是摸鱼日历的api出问题了

**Comment by ayahana** [comment]
> ![image](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/assets/88638705/cbeab417-4fd8-44aa-a3b6-4cc1899d4709)
> 用的最新版真寻（就是改过数据库的那个）

应该不是数据库的问题，是摸鱼日历的api出问题了

**Comment by 0wangxiaopang0** [comment]
真寻日志: ![image](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/assets/126732464/15c76d56-0c87-4091-b0ee-666ad076cd3d)

go-cqhttp日志： ![image](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/assets/126732464/40e105f0-c3aa-4b12-8c99-19ad411e8d24)
我也是这问题，定时推送失败

**Comment by ayahana** [comment]
好像又能用了 不知道怎么回事
