### ISSUE TITLE
Feat: add `bing ai聊天` plugin

### ISSUE THREAD

**Issue by xuyufenfei** [zhenxun-org/zhenxun_bot_plugins_index#196]
## 插件名

bing ai聊天

## GitHub 地址
https://github.com/xuyufenfei/zhenxun_bingo

## 备注

通过bingo，轻松的实现与bing ai聊天

## 下载地址（可选）

您插件的下载地址，必须为 GitHub Release 地址

**Comment by xuanerwa** [comment]
更新了
